server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: apidocumento
          uri: lb://api-documento
          predicates:
            - Path=/documentos/**
        - id: apipersona
          uri: lb://api-persona
          predicates:
            - Path=/personas/**